apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: semoss
  name: semoss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semoss
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: semoss
    spec:
      containers:
      - image: devopmacaz/semoss:1.0.0
        name: semoss
        resources: {}
status: {}
