apiVersion: v1
kind: Service
metadata:
  name: {{  printf "%s-%s"  .Values.env .Values.scheduler.name}}
  labels:
    app.kubernetes.io/name: {{ printf "%s-%s"  .Values.env .Values.scheduler.name}}
    helm.sh/chart: {{ include "semoss.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
    - port: {{ .Values.scheduler.service.port }}
      targetPort: {{ .Values.scheduler.service.port }}
      nodePort: {{ .Values.scheduler.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ printf "%s-%s"  .Values.env .Values.scheduler.name}}
    app.kubernetes.io/instance: {{ .Release.Name }}
