apiVersion: v1
kind: Service
metadata:
  name: {{  printf "%s-%s" .Values.env .Values.semoss.name  }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.env .Values.semoss.name  }}
    helm.sh/chart: {{ include "semoss.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.semoss.service.type }}
  ports:
    - port: {{ .Values.semoss.service.port }}
      targetPort: {{ .Values.semoss.service.port }}
      {{- if .Values.semoss.service.nodePort }}
      nodePort: {{ .Values.semoss.service.nodePort }}
      {{- end }}

  selector:
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.env .Values.semoss.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
